// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-iRVwdSUznhQbR0ob8N3IeRYNFeUEHlI',
    appId: '1:774242664448:web:6c109c2d3d884b4d87d8e5',
    messagingSenderId: '774242664448',
    projectId: 'indicai-2ba4d',
    authDomain: 'indicai-2ba4d.firebaseapp.com',
    storageBucket: 'indicai-2ba4d.firebasestorage.app',
    measurementId: 'G-X05CNXCVZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_fS2M7CgHzVWokHVuIQ8K1aIqjbW4vRY',
    appId: '1:774242664448:android:1d562e7a992085bf87d8e5',
    messagingSenderId: '774242664448',
    projectId: 'indicai-2ba4d',
    storageBucket: 'indicai-2ba4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzCMug4479QNm3PJgnylryWA36yuF0tiE',
    appId: '1:774242664448:ios:efcadb4ed14a5edc87d8e5',
    messagingSenderId: '774242664448',
    projectId: 'indicai-2ba4d',
    storageBucket: 'indicai-2ba4d.firebasestorage.app',
    iosClientId: '774242664448-d1jfdilms7etbvse24opf9ffenccu5hq.apps.googleusercontent.com',
    iosBundleId: 'com.example.indicai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzCMug4479QNm3PJgnylryWA36yuF0tiE',
    appId: '1:774242664448:ios:efcadb4ed14a5edc87d8e5',
    messagingSenderId: '774242664448',
    projectId: 'indicai-2ba4d',
    storageBucket: 'indicai-2ba4d.firebasestorage.app',
    iosClientId: '774242664448-d1jfdilms7etbvse24opf9ffenccu5hq.apps.googleusercontent.com',
    iosBundleId: 'com.example.indicai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-iRVwdSUznhQbR0ob8N3IeRYNFeUEHlI',
    appId: '1:774242664448:web:1ce810279827367b87d8e5',
    messagingSenderId: '774242664448',
    projectId: 'indicai-2ba4d',
    authDomain: 'indicai-2ba4d.firebaseapp.com',
    storageBucket: 'indicai-2ba4d.firebasestorage.app',
    measurementId: 'G-D8HX5LE05Q',
  );
}
